<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrestaFacil.Domain\PrestaFacil.Domain.csproj" />
    <ProjectReference Include="..\PrestaFacil.Infrastructure\PrestaFacil.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
  </ItemGroup>

</Project>
